baseURL = "https://kpinney.github.io/"
languageCode = "en-us"
title = "My Personal Webpage"
theme = "ananke"
publishDir = "docs"

[params]
  author = "Your Name"

[markup.goldmark.renderer]
  unsafe = true
